### ISSUE TITLE
concatTx function has wrong signature

### ISSUE THREAD

**Issue by friedger** [web3devs/stacks-bitcoin-api#6]
The clartiy function contactTx only accepts `buff` types but the the js function expectes `TupleCV<TxDataCV>` that contains uintCV types.

concatTx function is used in catamaranswap: https://github.com/boomcrypto/clarity-mainnet-contracts/blob/main/contracts/SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9/btc-stx-swap-v1.clar#L58

It is an important function because parseTx was too expensive to execute on-chain. Is this still the case after Stacks 2.05?

**Comment by bgok** [comment]
Hmm. Interesting. It is working when called on testnet, but I haven't really been paying attention to the gas cost.

**Comment by bgok** [comment]
The signature of the concat-tx function is as follows here: https://github.com/friedger/clarity-catamaranswaps/blob/bb552b99ac7abf78c3b4f53b3516e27024595dc9/contracts/clarity-bitcoin.clar#L772
```
    (concat-tx 
        (tx {
            version: (buff 4),
            ins: (list 8 {
                outpoint: {
                    hash: (buff 32), index: (buff 4)
                },
                scriptSig: (buff 127), 
                sequence: (buff 4
            )}),
            outs: (list 8 {
                value: (buff 8), 
                scriptPubKey: (buff 127)
            }),
            locktime: (buff 4)
        })
    )
```
The function to call it from JS is dead code in the test directory, so it may not matter. Since you requested that the ClarityBitcoinClient.js be moved from the test directory into the API in issue #12, I will re-evaluate when addressing that issue.

Regarding the execution cost of parse-tx, I will address with issue #8.
