### ISSUE TITLE
Clarify the difference and use of txs in decompacte tuples and compacted buffer

### ISSUE THREAD

**Issue by friedger** [web3devs/stacks-bitcoin-api#7]
Coming soon states: 
> A contract endpoint and supporting API code to pass a transaction as a decompacted tuple instead of as a compacted buffer. This will enable contracts that use this API to easily extract values from the contract. Is this needed since the tx can be parsed with `parsetx`?

This should be explained in the readme #5 and/or example code.

**Comment by friedger** [comment]
There is `was-tx-mined-compact`and `was-tx-mined` in the v1 of the bitcoin-lib.clar. Is that enough?

**Comment by bgok** [comment]
The coming soon section of the README was removed because the issues described there have been converted to github issues.

The original question referenced above was asking whether it is ok to always supply the raw transaction buffer for verification and rely on `parse-tx` to get the details from the transaction. When addressing issue #8, I will compare relative the transaction cost of parsing a raw transaction buffer (compacted) into its fields -vs- the cost of supplying the values of the individual fields and composing them into a compacted transaction.

The difference between `was-tx-mined-compact` and `was-tx-mined` is whether the block header is passed as a buffer or as a tuple. The tx details are passed as a buffer in both functions.
